1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

arr1 = np.random.randint(1,21,(5,5))
print(arr1)

# replace elements
print('-------------------')
arr1[:,2] = 1
print(arr1)


[[ 5 16 18 13  6]
 [ 4  4 10 13 14]
 [17  1 14 14 11]
 [20  7  4 16 13]
 [ 7  7  7  4 12]]
-------------------
[[ 5 16  1 13  6]
 [ 4  4  1 13 14]
 [17  1  1 14 11]
 [20  7  1 16 13]
 [ 7  7  1  4 12]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr2 = np.random.randint(1,17,(4,4))
print(arr2)

print('-------------------')
np.fill_diagonal(arr2 , 0)
print(arr2)

[[ 5 14 10  9]
 [ 2 10 15  4]
 [16  5 14 15]
 [16 12  4 10]]
-------------------
[[ 0 14 10  9]
 [ 2  0 15  4]
 [16  5  0 15]
 [16 12  4  0]]


3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
arr3 = np.random.randint(1,37,(6,6))
print(arr3)

print('-------------------')
print(arr3[2:5,1:4])


[[28 29 31 27  4 17]
 [16 31 17 23 20  4]
 [35 26 23 20 23 25]
 [22 29 36 15  1 17]
 [22 32 19 35 10  7]
 [11  5 12  2  4 15]]
-------------------
[[26 23 20]
 [29 36 15]
 [32 19 35]]


4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr = np.random.randint(1,26,(5,5))
print(arr)

print('-------------------')
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_elements)

[[ 8  4 16  3 13]
 [ 9 18  7  6  2]
 [ 4 22 20  6  4]
 [ 4 22  8  3 11]
 [10 18  8  3 25]]
-------------------
[ 8  4 16  3 13 10 18  8  3 25  9  4  4  2  4 11]


5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))
print(arr1)
print("-----------------")
print(arr2)
print("Addition:")
print(arr1 + arr2)
print("Subtraction:")
print(arr1 - arr2)
print("Multiplication:")
print(arr1 * arr2)
print("Division:")
print(arr1 / arr2)


[[29 15 17 26]
 [10  6  2 27]
 [20  6  8  6]]
-----------------
[[11 20 11 20]
 [24  9 12 11]
 [ 4  8  3 17]]
Addition:
[[40 35 28 46]
 [34 15 14 38]
 [24 14 11 23]]
Subtraction:
[[ 18  -5   6   6]
 [-14  -3 -10  16]
 [ 16  -2   5 -11]]
Multiplication:
[[319 300 187 520]
 [240  54  24 297]
 [ 80  48  24 102]]
Division:
[[2.63636364 0.75       1.54545455 1.3       ]
 [0.41666667 0.66666667 0.16666667 2.45454545]
 [5.         0.75       2.66666667 0.35294118]]


6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

print("Using np.sum")
row_wise_addition = np.sum(arr1,axis=1)
col_wise_addition = np.sum(arr1,axis=0)
print('Row wise addition: ',row_wise_addition)
print('Col wise addition: ',col_wise_addition)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Using np.sum
Row wise addition:  [10 26 42 58]
Col wise addition:  [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [8]:
array = np.random.randint(1, 21, size=(5, 5))
print(array)
print("Mean: ",np.mean(array))
print("Median: ",np.median(array))
print("STD: ",np.std(array))
print("Variance: ",np.var(array))

[[18  4 20  2 11]
 [18 18  2  8  3]
 [ 8 10  1  7 17]
 [19 19 10  4 11]
 [ 1  3 13  2 11]]
Mean:  9.6
Median:  10.0
STD:  6.486909896090742
Variance:  42.08


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_array = (arr-mean) / std_dev

print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
arr = np.random.randint(1,10,(3,3))
print("array:\n",arr)

array_1D = np.random.randint(1,10,(3,))
print("1_D_array:\n",array_1D)

result = arr + array_1D
print("Result:\n",result)

array:
 [[7 5 9]
 [6 1 9]
 [6 3 4]]
1_D_array:
 [8 1 9]
Result:
 [[15  6 18]
 [14  2 18]
 [14  4 13]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr = np.random.randint(1,17,(4,4))
print("Array:\n",arr)

arr_1D = np.random.randint(1,10,(4,))
print("1D_Array:\n",arr_1D)

arr_subtract = arr - arr_1D[:,np.newaxis]
print(arr_subtract)


Array:
 [[16 16 16  6]
 [16  6 12 15]
 [10 12  4 16]
 [ 5  2 11 15]]
1D_Array:
 [4 5 8 9]
[[12 12 12  2]
 [11  1  7 10]
 [ 2  4 -4  8]
 [-4 -7  2  6]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [12]:
arr = np.random.randint(1,10,(3,3))
print(arr)
print("Determinant:\n",np.linalg.det(arr))
print("Inverse:\n",np.linalg.inv(arr))
print("EigenValues:\n",np.linalg.eigvals(arr))


[[4 6 8]
 [3 6 9]
 [8 1 3]]
Determinant:
 54.00000000000003
Inverse:
 [[ 0.16666667 -0.18518519  0.11111111]
 [ 1.16666667 -0.96296296 -0.22222222]
 [-0.83333333  0.81481481  0.11111111]]
EigenValues:
 [15.59465366+0.j         -1.29732683+1.33404208j -1.29732683-1.33404208j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
arr1 = np.random.randint(1,9,(2,3))
arr2 = np.random.randint(1,9,(3,2))
print("Array 1:\n",arr1)
print("Array 2:\n",arr2)
result = np.dot(arr1,arr2)
print(result)

Array 1:
 [[6 4 7]
 [5 4 3]]
Array 2:
 [[6 3]
 [8 8]
 [3 1]]
[[89 57]
 [71 50]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
arr = np.random.randint(1,10,(3,3))
print(arr)
arr2 = arr.reshape(1,9)
print(arr2)
arr3 = arr.reshape(9,1)
print(arr3)

[[6 8 4]
 [8 9 1]
 [9 7 6]]
[[6 8 4 8 9 1 9 7 6]]
[[6]
 [8]
 [4]
 [8]
 [9]
 [1]
 [9]
 [7]
 [6]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
arr = np.random.randint(1,26,(5,5))
print(arr)
arr2 = arr.flatten()
print("________")
print(arr2)
print("________")
print(arr2.reshape(1,25))


[[19 19 13  4 14]
 [10  6  8  9 22]
 [25 24 24 13  2]
 [15  6  3  7 22]
 [17 13  8 22 18]]
________
[19 19 13  4 14 10  6  8  9 22 25 24 24 13  2 15  6  3  7 22 17 13  8 22
 18]
________
[[19 19 13  4 14 10  6  8  9 22 25 24 24 13  2 15  6  3  7 22 17 13  8 22
  18]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [16]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)
print("__________________")
# using concatenation
print(arr[[0,0,-1,-1],[0,-1,0,-1]])


[[ 7 11 24  8 24]
 [16 16  2 21 13]
 [13 18 13  5 10]
 [19  4 23 23  5]
 [15  4 17 18 10]]
__________________
[ 7 24 15 10]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [22]:
arr = np.random.randint(1,20,size = (4,4))
print(arr)
arr[arr>10]=10

print(arr)

[[10  7 11 16]
 [17  2 14  9]
 [14 15 13 10]
 [ 7  1  4 10]]
[[10  7 10 10]
 [10  2 10  9]
 [10 10 10 10]
 [ 7  1  4 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [ ]:
data = [('name','U10'),('age','i4')]