1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [3]:
import numpy as np

arr1 = np.random.randint(1,21,(5,5))
print(arr1)

# replace elements
print('-------------------')
arr1[:,2] = 1
print(arr1)


[[ 2 15 11 19 15]
 [10  7 11 18 16]
 [12 16  4  8 13]
 [ 9 12  2 16  8]
 [17  5  9  3 12]]
-------------------
[[ 2 15  1 19 15]
 [10  7  1 18 16]
 [12 16  1  8 13]
 [ 9 12  1 16  8]
 [17  5  1  3 12]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
arr2 = np.random.randint(1,17,(4,4))
print(arr2)

print('-------------------')
np.fill_diagonal(arr2 , 0)
print(arr2)

[[14  2 14  3]
 [ 7  1  5  9]
 [ 2 12  8 10]
 [ 6  3  4  6]]
-------------------
[[ 0  2 14  3]
 [ 7  0  5  9]
 [ 2 12  0 10]
 [ 6  3  4  0]]


3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [5]:
arr3 = np.random.randint(1,37,(6,6))
print(arr3)

print('-------------------')
print(arr3[2:5,1:4])


[[34 22 33 32 15 19]
 [29 14 13 23 27 27]
 [27 26 22  5 27 29]
 [10  1  1 18 31 29]
 [26  1 24 30 16  4]
 [29 24 29 14 33  9]]
-------------------
[[26 22  5]
 [ 1  1 18]
 [ 1 24 30]]


4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [6]:
arr = np.random.randint(1,26,(5,5))
print(arr)

print('-------------------')
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_elements)

[[11 17  4  9  5]
 [24  6 20 19 12]
 [ 2 12  6 25 19]
 [11 14  1 15  5]
 [24 13  8 10 15]]
-------------------
[11 17  4  9  5 24 13  8 10 15 24  2 11 12 19  5]


5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [7]:
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))
print(arr1)
print("-----------------")
print(arr2)
print("Addition:")
print(arr1 + arr2)
print("Subtraction:")
print(arr1 - arr2)
print("Multiplication:")
print(arr1 * arr2)
print("Division:")
print(arr1 / arr2)


[[26 23 15 12]
 [29  3 12  6]
 [ 4 14 19  5]]
-----------------
[[27 19 15 19]
 [18 18 28  5]
 [20  8 22 28]]
Addition:
[[53 42 30 31]
 [47 21 40 11]
 [24 22 41 33]]
Subtraction:
[[ -1   4   0  -7]
 [ 11 -15 -16   1]
 [-16   6  -3 -23]]
Multiplication:
[[702 437 225 228]
 [522  54 336  30]
 [ 80 112 418 140]]
Division:
[[0.96296296 1.21052632 1.         0.63157895]
 [1.61111111 0.16666667 0.42857143 1.2       ]
 [0.2        1.75       0.86363636 0.17857143]]


6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [8]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

print("Using np.sum")
row_wise_addition = np.sum(arr1,axis=1)
col_wise_addition = np.sum(arr1,axis=0)
print('Row wise addition: ',row_wise_addition)
print('Col wise addition: ',col_wise_addition)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Using np.sum
Row wise addition:  [10 26 42 58]
Col wise addition:  [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [9]:
array = np.random.randint(1, 21, size=(5, 5))
print(array)
print("Mean: ",np.mean(array))
print("Median: ",np.median(array))
print("STD: ",np.std(array))
print("Variance: ",np.var(array))

[[ 6 14 10 11  3]
 [ 1 19 13 12 14]
 [ 5 12  2  2 19]
 [ 2  1 18 17 15]
 [18 11 16 18 17]]
Mean:  11.04
Median:  12.0
STD:  6.264056193873104
Variance:  39.2384


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [10]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_array = (arr-mean) / std_dev

print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [11]:
arr = np.random.randint(1,10,(3,3))
print("array:\n",arr)

array_1D = np.random.randint(1,10,(3,))
print("1_D_array:\n",array_1D)

result = arr + array_1D
print("Result:\n",result)

array:
 [[5 8 3]
 [1 4 1]
 [6 5 4]]
1_D_array:
 [2 1 2]
Result:
 [[7 9 5]
 [3 5 3]
 [8 6 6]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [12]:
arr = np.random.randint(1,17,(4,4))
print("Array:\n",arr)

arr_1D = np.random.randint(1,10,(4,))
print("1D_Array:\n",arr_1D)

arr_subtract = arr - arr_1D[:,np.newaxis]
print(arr_subtract)


Array:
 [[ 5 14  5  3]
 [13  1  5  6]
 [11 14  3  4]
 [14  6  2  3]]
1D_Array:
 [7 5 9 4]
[[-2  7 -2 -4]
 [ 8 -4  0  1]
 [ 2  5 -6 -5]
 [10  2 -2 -1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [13]:
arr = np.random.randint(1,10,(3,3))
print(arr)
print("Determinant:\n",np.linalg.det(arr))
print("Inverse:\n",np.linalg.inv(arr))
print("EigenValues:\n",np.linalg.eigvals(arr))


[[9 6 3]
 [7 9 4]
 [1 9 1]]
Determinant:
 -98.99999999999999
Inverse:
 [[ 0.27272727 -0.21212121  0.03030303]
 [ 0.03030303 -0.06060606  0.15151515]
 [-0.54545455  0.75757576 -0.39393939]]
EigenValues:
 [17.6636555  3.1280875 -1.791743 ]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [14]:
arr1 = np.random.randint(1,9,(2,3))
arr2 = np.random.randint(1,9,(3,2))
print("Array 1:\n",arr1)
print("Array 2:\n",arr2)
result = np.dot(arr1,arr2)
print(result)

Array 1:
 [[1 5 4]
 [5 3 6]]
Array 2:
 [[8 4]
 [8 8]
 [4 1]]
[[64 48]
 [88 50]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [15]:
arr = np.random.randint(1,10,(3,3))
print(arr)
arr2 = arr.reshape(1,9)
print(arr2)
arr3 = arr.reshape(9,1)
print(arr3)

[[2 8 6]
 [9 4 7]
 [6 4 1]]
[[2 8 6 9 4 7 6 4 1]]
[[2]
 [8]
 [6]
 [9]
 [4]
 [7]
 [6]
 [4]
 [1]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [16]:
arr = np.random.randint(1,26,(5,5))
print(arr)
arr2 = arr.flatten()
print("________")
print(arr2)
print("________")
print(arr2.reshape(1,25))


[[21 15 24 17 22]
 [16  9  5  8 18]
 [11 17 24 22 22]
 [23 25 17  1 14]
 [ 9 21 20 15 12]]
________
[21 15 24 17 22 16  9  5  8 18 11 17 24 22 22 23 25 17  1 14  9 21 20 15
 12]
________
[[21 15 24 17 22 16  9  5  8 18 11 17 24 22 22 23 25 17  1 14  9 21 20 15
  12]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [17]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)
print("__________________")
# using concatenation
print(arr[[0,0,-1,-1],[0,-1,0,-1]])


[[21 14 22 13  5]
 [12 16 21  5 15]
 [20  2 16  3 23]
 [16  6  2  7 21]
 [20 15 23 24  2]]
__________________
[21  5 20  2]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [18]:
arr = np.random.randint(1,20,size = (4,4))
print(arr)
arr[arr>10]=10

print(arr)

[[ 1 11 19 12]
 [ 4  5 12  7]
 [19  9 12 15]
 [19  6  2  5]]
[[ 1 10 10 10]
 [ 4  5 10  7]
 [10  9 10 10]
 [10  6  2  5]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [23]:
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([
    ('rocky',24,65.5),
    ('tocky',26,56.1),
    ('vocky',28,86.2)
],dtype=data_type)
print(data)

[('rocky', 24, 65.5) ('tocky', 26, 56.1) ('vocky', 28, 86.2)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
data_type = [('X','i4'),('Y','i4')]
data = np.array([
    (1,3),
    (2,5),
    (4,7),
    (2,4)
    ],dtype=data_type)

print(data)
dist_formula = np.sqrt((data['X'][:,np.newaxis] - (data['Y'][:,np.newaxis])))


[(1, 3) (2, 5) (4, 7) (2, 4)]
