1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [14]:
import numpy as np

arr1 = np.random.randint(1,21,(5,5))
print(arr1)

# replace elements
print('-------------------')
arr1[:,2] = 1
print(arr1)


[[ 5 17 17  2 15]
 [10 20  6  4 19]
 [ 1 18  3  5  4]
 [ 5 17 17  1  3]
 [20  8 11  4 13]]
-------------------
[[ 5 17  1  2 15]
 [10 20  1  4 19]
 [ 1 18  1  5  4]
 [ 5 17  1  1  3]
 [20  8  1  4 13]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [17]:
arr2 = np.random.randint(1,17,(4,4))
print(arr2)

print('-------------------')
np.fill_diagonal(arr2 , 0)
print(arr2)

[[15 11 13  1]
 [10  7  1  3]
 [12 10  9  8]
 [10  7 14 13]]
-------------------
[[ 0 11 13  1]
 [10  0  1  3]
 [12 10  0  8]
 [10  7 14  0]]


3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [24]:
arr3 = np.random.randint(1,37,(6,6))
print(arr3)

print('-------------------')
print(arr3[2:5,1:4])


[[12 22 34 36 30 23]
 [ 3 24 11 11 34  2]
 [32 13 22  9 17 21]
 [28 36 26  8  5 32]
 [13 31  6  1 22  7]
 [34 19 13  5 18 13]]
-------------------
[[13 22  9]
 [36 26  8]
 [31  6  1]]


4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [45]:
arr = np.random.randint(1,26,(5,5))
print(arr)

print('-------------------')
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_elements)

[[ 2  1 25 13  4]
 [20 24  7  4 19]
 [24  8  7  6  4]
 [16 25 18  7 15]
 [11 20 24  3  4]]
-------------------
[ 2  1 25 13  4 11 20 24  3  4 20 24 16 19  4 15]


5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))
print(arr1)
print("-----------------")
print(arr2)
print("Addition:")
print(arr1 + arr2)
print("Subtraction:")
print(arr1 - arr2)
print("Multiplication:")
print(arr1 * arr2)
print("Division:")
print(arr1 / arr2)


[[ 5 28 26  7]
 [26  8  5  5]
 [18 24 14  3]]
-----------------
[[ 9  1 16 24]
 [ 9 29  1 29]
 [24 25 24 29]]
Addition:
[[14 29 42 31]
 [35 37  6 34]
 [42 49 38 32]]
Subtraction:
[[ -4  27  10 -17]
 [ 17 -21   4 -24]
 [ -6  -1 -10 -26]]
Multiplication:
[[ 45  28 416 168]
 [234 232   5 145]
 [432 600 336  87]]
Division:
[[ 0.55555556 28.          1.625       0.29166667]
 [ 2.88888889  0.27586207  5.          0.17241379]
 [ 0.75        0.96        0.58333333  0.10344828]]


6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [66]:
arr1 = np.random.randint(1,16,(4,4))
print(arr1)

addition_rows = arr1[0,0:] + arr1[-1:]
addition_cols = arr1[0:,0:] + arr1[0:,-1] 
print("Row_wise_Add:",addition_rows)
print("Col_wise_Add:",addition_cols)

[[ 9 10 12 15]
 [ 8  5 13  6]
 [ 6  8 14 13]
 [ 7 15  5  8]]
Row_wise_Add: [[16 25 17 23]]
Col_wise_Add: [[24 16 25 23]
 [23 11 26 14]
 [21 14 27 21]
 [22 21 18 16]]
