1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

arr1 = np.random.randint(1,21,(5,5))
print(arr1)

# replace elements
print('-------------------')
arr1[:,2] = 1
print(arr1)


[[14  3 15  7  4]
 [ 4  5 20  7 19]
 [18  3 14 10 16]
 [12 11 11  2  3]
 [ 4 19  2 11  5]]
-------------------
[[14  3  1  7  4]
 [ 4  5  1  7 19]
 [18  3  1 10 16]
 [12 11  1  2  3]
 [ 4 19  1 11  5]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr2 = np.random.randint(1,17,(4,4))
print(arr2)

print('-------------------')
np.fill_diagonal(arr2 , 0)
print(arr2)

[[ 8 13  9 15]
 [13  5  8  3]
 [ 8  5  7 16]
 [ 9 13 15 15]]
-------------------
[[ 0 13  9 15]
 [13  0  8  3]
 [ 8  5  0 16]
 [ 9 13 15  0]]


3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
arr3 = np.random.randint(1,37,(6,6))
print(arr3)

print('-------------------')
print(arr3[2:5,1:4])


[[35 30 17 14  3 34]
 [34 32 23 30 12 21]
 [ 8 36  6 30 11 24]
 [10 30 31 18  9  9]
 [ 5  5 21  4 11 19]
 [ 7 27 30 10 29 33]]
-------------------
[[36  6 30]
 [30 31 18]
 [ 5 21  4]]


4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
arr = np.random.randint(1,26,(5,5))
print(arr)

print('-------------------')
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_elements)

[[12  1 11 17 17]
 [12  7  1 16  3]
 [14 11 17 14  3]
 [10 13 18 11 19]
 [ 8 16 10 17 24]]
-------------------
[12  1 11 17 17  8 16 10 17 24 12 14 10  3  3 19]


5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))
print(arr1)
print("-----------------")
print(arr2)
print("Addition:")
print(arr1 + arr2)
print("Subtraction:")
print(arr1 - arr2)
print("Multiplication:")
print(arr1 * arr2)
print("Division:")
print(arr1 / arr2)


[[ 3  8  4 25]
 [11 19 25  1]
 [27 26  8 15]]
-----------------
[[18 17 14 26]
 [17 20 11 23]
 [14 19 20 14]]
Addition:
[[21 25 18 51]
 [28 39 36 24]
 [41 45 28 29]]
Subtraction:
[[-15  -9 -10  -1]
 [ -6  -1  14 -22]
 [ 13   7 -12   1]]
Multiplication:
[[ 54 136  56 650]
 [187 380 275  23]
 [378 494 160 210]]
Division:
[[0.16666667 0.47058824 0.28571429 0.96153846]
 [0.64705882 0.95       2.27272727 0.04347826]
 [1.92857143 1.36842105 0.4        1.07142857]]


6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

print("Using np.sum")
row_wise_addition = np.sum(arr1,axis=1)
col_wise_addition = np.sum(arr1,axis=0)
print('Row wise addition: ',row_wise_addition)
print('Col wise addition: ',col_wise_addition)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Using np.sum
Row wise addition:  [10 26 42 58]
Col wise addition:  [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [8]:
array = np.random.randint(1, 21, size=(5, 5))
print(array)
print("Mean: ",np.mean(array))
print("Median: ",np.median(array))
print("STD: ",np.std(array))
print("Variance: ",np.var(array))

[[13 10 10  2 12]
 [20 19  2  1  1]
 [15  1  5 14  2]
 [ 8 16  1 10 13]
 [20 15  9 18  3]]
Mean:  9.6
Median:  10.0
STD:  6.511528238439882
Variance:  42.4


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_array = (arr-mean) / std_dev

print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
arr = np.random.randint(1,10,(3,3))
print("array:\n",arr)

array_1D = np.random.randint(1,10,(3,))
print("1_D_array:\n",array_1D)

result = arr + array_1D
print("Result:\n",result)

array:
 [[8 1 2]
 [3 6 2]
 [9 2 6]]
1_D_array:
 [8 5 1]
Result:
 [[16  6  3]
 [11 11  3]
 [17  7  7]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
arr = np.random.randint(1,17,(4,4))
print("Array:\n",arr)

arr_1D = np.random.randint(1,10,(4,))
print("1D_Array:\n",arr_1D)

arr_subtract = arr - arr_1D[:,np.newaxis]
print(arr_subtract)


Array:
 [[14  4  7 14]
 [ 3  6 16  2]
 [ 8  9 12 14]
 [ 4  2  1 13]]
1D_Array:
 [6 5 1 2]
[[ 8 -2  1  8]
 [-2  1 11 -3]
 [ 7  8 11 13]
 [ 2  0 -1 11]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [12]:
arr = np.random.randint(1,10,(3,3))
print(arr)
print("Determinant:\n",np.linalg.det(arr))
print("Inverse:\n",np.linalg.inv(arr))
print("EigenValues:\n",np.linalg.eigvals(arr))


[[6 7 2]
 [1 6 7]
 [9 4 6]]
Determinant:
 347.00000000000006
Inverse:
 [[ 0.02305476 -0.09798271  0.10662824]
 [ 0.16426513  0.0518732  -0.11527378]
 [-0.14409222  0.11239193  0.08357349]]
EigenValues:
 [15.91408582+0.j         1.04295709+4.5515737j  1.04295709-4.5515737j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
arr1 = np.random.randint(1,9,(2,3))
arr2 = np.random.randint(1,9,(3,2))
print("Array 1:\n",arr1)
print("Array 2:\n",arr2)
result = np.dot(arr1,arr2)
print(result)

Array 1:
 [[5 6 2]
 [2 6 7]]
Array 2:
 [[6 8]
 [1 6]
 [6 7]]
[[ 48  90]
 [ 60 101]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
arr = np.random.randint(1,10,(3,3))
print(arr)
arr2 = arr.reshape(1,9)
print(arr2)
arr3 = arr.reshape(9,1)
print(arr3)

[[5 3 3]
 [8 8 7]
 [9 5 2]]
[[5 3 3 8 8 7 9 5 2]]
[[5]
 [3]
 [3]
 [8]
 [8]
 [7]
 [9]
 [5]
 [2]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
arr = np.random.randint(1,26,(5,5))
print(arr)
arr2 = arr.flatten()
print("________")
print(arr2)
print("________")
print(arr2.reshape(1,25))


[[23 15 22 23 23]
 [19 18  4 10 12]
 [ 4 20 21  6 16]
 [ 1 19  8 15 15]
 [ 2 25 18 19  1]]
________
[23 15 22 23 23 19 18  4 10 12  4 20 21  6 16  1 19  8 15 15  2 25 18 19
  1]
________
[[23 15 22 23 23 19 18  4 10 12  4 20 21  6 16  1 19  8 15 15  2 25 18 19
   1]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [56]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)
print("__________________")
# using concatenation
print(arr[[0,0,-1,-1],[0,-1,0,-1]])


[[ 6 16  2 22  9]
 [22 18  3 25 16]
 [ 4 25  3 21 17]
 [20  3  8  8 19]
 [22 19 15  4 11]]
__________________
[ 6  9 22 11]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.