1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

arr1 = np.random.randint(1,21,(5,5))
print(arr1)

# replace elements
print('-------------------')
arr1[:,2] = 1
print(arr1)


[[ 6  8 10 16  7]
 [16 13 18  4 15]
 [ 3 10  6 12 14]
 [ 8 12  1 14 15]
 [ 2 15 13 16  4]]
-------------------
[[ 6  8  1 16  7]
 [16 13  1  4 15]
 [ 3 10  1 12 14]
 [ 8 12  1 14 15]
 [ 2 15  1 16  4]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
arr2 = np.random.randint(1,17,(4,4))
print(arr2)

print('-------------------')
np.fill_diagonal(arr2 , 0)
print(arr2)

[[ 4  7  6  7]
 [ 8  3  7 11]
 [ 6  5  4  1]
 [ 2 11  5  2]]
-------------------
[[ 0  7  6  7]
 [ 8  0  7 11]
 [ 6  5  0  1]
 [ 2 11  5  0]]


3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [3]:
arr3 = np.random.randint(1,37,(6,6))
print(arr3)

print('-------------------')
print(arr3[2:5,1:4])


[[26 13 13 36 23  5]
 [10 28 32 15  8 23]
 [18  8  7 21 12  8]
 [ 5 14 33 19 22 12]
 [ 9  1 31 14 10 27]
 [31 22 29 35 15 12]]
-------------------
[[ 8  7 21]
 [14 33 19]
 [ 1 31 14]]


4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
arr = np.random.randint(1,26,(5,5))
print(arr)

print('-------------------')
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_elements)

[[12 16 19  7 23]
 [23 11  2  8 19]
 [16 20 19 12 12]
 [19 21 11  2 10]
 [ 5  6  3 21 23]]
-------------------
[12 16 19  7 23  5  6  3 21 23 23 16 19 19 12 10]


5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [5]:
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))
print(arr1)
print("-----------------")
print(arr2)
print("Addition:")
print(arr1 + arr2)
print("Subtraction:")
print(arr1 - arr2)
print("Multiplication:")
print(arr1 * arr2)
print("Division:")
print(arr1 / arr2)


[[ 4 22  1 20]
 [13 17 27 13]
 [ 6 13 15 24]]
-----------------
[[20 16 24 21]
 [28 21 18 11]
 [ 1 10 12 15]]
Addition:
[[24 38 25 41]
 [41 38 45 24]
 [ 7 23 27 39]]
Subtraction:
[[-16   6 -23  -1]
 [-15  -4   9   2]
 [  5   3   3   9]]
Multiplication:
[[ 80 352  24 420]
 [364 357 486 143]
 [  6 130 180 360]]
Division:
[[0.2        1.375      0.04166667 0.95238095]
 [0.46428571 0.80952381 1.5        1.18181818]
 [6.         1.3        1.25       1.6       ]]


6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

print("Using np.sum")
row_wise_addition = np.sum(arr1,axis=1)
col_wise_addition = np.sum(arr1,axis=0)
print('Row wise addition: ',row_wise_addition)
print('Col wise addition: ',col_wise_addition)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Using np.sum
Row wise addition:  [10 26 42 58]
Col wise addition:  [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [7]:
array = np.random.randint(1, 21, size=(5, 5))
print(array)
print("Mean: ",np.mean(array))
print("Median: ",np.median(array))
print("STD: ",np.std(array))
print("Variance: ",np.var(array))

[[11 16 19 10  3]
 [ 8 15  9  7  8]
 [13  3  4 20 19]
 [13  5 17 11 14]
 [ 3  2 11 18  5]]
Mean:  10.56
Median:  11.0
STD:  5.586268880030749
Variance:  31.2064


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_array = (arr-mean) / std_dev

print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [9]:
arr = np.random.randint(1,10,(3,3))
print("array:\n",arr)

array_1D = np.random.randint(1,10,(3,))
print("1_D_array:\n",array_1D)

result = arr + array_1D
print("Result:\n",result)

array:
 [[2 9 2]
 [5 6 2]
 [5 8 3]]
1_D_array:
 [6 8 5]
Result:
 [[ 8 17  7]
 [11 14  7]
 [11 16  8]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [10]:
arr = np.random.randint(1,17,(4,4))
print("Array:\n",arr)

arr_1D = np.random.randint(1,10,(4,))
print("1D_Array:\n",arr_1D)

arr_subtract = arr - arr_1D[:,np.newaxis]
print(arr_subtract)


Array:
 [[13 11  1  8]
 [ 8  8  8 10]
 [ 3 15 15  5]
 [16  5  9 15]]
1D_Array:
 [3 1 6 5]
[[10  8 -2  5]
 [ 7  7  7  9]
 [-3  9  9 -1]
 [11  0  4 10]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [11]:
arr = np.random.randint(1,10,(3,3))
print(arr)
print("Determinant:\n",np.linalg.det(arr))
print("Inverse:\n",np.linalg.inv(arr))
print("EigenValues:\n",np.linalg.eigvals(arr))


[[3 4 2]
 [1 3 8]
 [9 5 6]]
Determinant:
 154.00000000000006
Inverse:
 [[-1.42857143e-01 -9.09090909e-02  1.68831169e-01]
 [ 4.28571429e-01  4.54182146e-17 -1.42857143e-01]
 [-1.42857143e-01  1.36363636e-01  3.24675325e-02]]
EigenValues:
 [14.+0.j         -1.+3.16227766j -1.-3.16227766j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [12]:
arr1 = np.random.randint(1,9,(2,3))
arr2 = np.random.randint(1,9,(3,2))
print("Array 1:\n",arr1)
print("Array 2:\n",arr2)
result = np.dot(arr1,arr2)
print(result)

Array 1:
 [[1 7 8]
 [6 7 4]]
Array 2:
 [[8 4]
 [5 7]
 [5 8]]
[[ 83 117]
 [103 105]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [13]:
arr = np.random.randint(1,10,(3,3))
print(arr)
arr2 = arr.reshape(1,9)
print(arr2)
arr3 = arr.reshape(9,1)
print(arr3)

[[3 7 6]
 [8 2 2]
 [5 7 1]]
[[3 7 6 8 2 2 5 7 1]]
[[3]
 [7]
 [6]
 [8]
 [2]
 [2]
 [5]
 [7]
 [1]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [ ]:
arr = np.random.randint(1,26,(5,5))
print(arr)
arr2 = arr.flatten()
print("________")
print(arr2)
print("________")
print(arr2.reshape(1,25))


[[23 16  4  5 13]
 [16 10 10  5  1]
 [18 15 22  5 10]
 [14 10  4  8  3]
 [ 9  2 17 14 12]]
________
[23 16  4  5 13 16 10 10  5  1 18 15 22  5 10 14 10  4  8  3  9  2 17 14
 12]
________
[[23 16  4  5 13 16 10 10  5  1 18 15 22  5 10 14 10  4  8  3  9  2 17 14
  12]]
