1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [10]:
import numpy as np

arr1 = np.random.randint(1,21,(5,5))
print(arr1)

# replace elements
print('-------------------')
arr1[:,2] = 1
print(arr1)


[[ 1 14  5  7 17]
 [ 4  9  3 15  4]
 [ 2 13 10  3 19]
 [12  9  7  5 18]
 [ 6 12 16 20 19]]
-------------------
[[ 1 14  1  7 17]
 [ 4  9  1 15  4]
 [ 2 13  1  3 19]
 [12  9  1  5 18]
 [ 6 12  1 20 19]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [11]:
arr2 = np.random.randint(1,17,(4,4))
print(arr2)

print('-------------------')
np.fill_diagonal(arr2 , 0)
print(arr2)

[[ 2  3  6  8]
 [16 12 15 11]
 [ 8  1  1 11]
 [ 2 13  1  1]]
-------------------
[[ 0  3  6  8]
 [16  0 15 11]
 [ 8  1  0 11]
 [ 2 13  1  0]]


3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [12]:
arr3 = np.random.randint(1,37,(6,6))
print(arr3)

print('-------------------')
print(arr3[2:5,1:4])


[[ 6 34 34 12 25  5]
 [25 13 24  3 22 15]
 [26  3  4 16 18  5]
 [22 34 25 18  1  8]
 [17 19 32 15 22 27]
 [ 2 35 17 33 36 17]]
-------------------
[[ 3  4 16]
 [34 25 18]
 [19 32 15]]


4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [ ]:
arr = np.random.randint(1,26,(5,5))
print(arr)

print('-------------------')
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_elements)

[[22 12 22  8 13]
 [ 8 24 21  1  7]
 [13  9  4 25 19]
 [16 23  8 22  3]
 [18 22 15 13  3]]
-------------------
[22 12 22  8 13 18 22 15 13  3  8 13 16  7 19  3]


5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))
print(arr1)
print("-----------------")
print(arr2)
print("Addition:")
print(arr1 + arr2)
print("Subtraction:")
print(arr1 - arr2)
print("Multiplication:")
print(arr1 * arr2)
print("Division:")
print(arr1 / arr2)


[[21 23 12 25]
 [25  3 27 22]
 [ 7 17 27 22]]
-----------------
[[18 14 18 18]
 [25  6 21 25]
 [27  3 22 23]]
Addition:
[[39 37 30 43]
 [50  9 48 47]
 [34 20 49 45]]
Subtraction:
[[  3   9  -6   7]
 [  0  -3   6  -3]
 [-20  14   5  -1]]
Multiplication:
[[378 322 216 450]
 [625  18 567 550]
 [189  51 594 506]]
Division:
[[1.16666667 1.64285714 0.66666667 1.38888889]
 [1.         0.5        1.28571429 0.88      ]
 [0.25925926 5.66666667 1.22727273 0.95652174]]


6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
arr1 = np.random.randint(1,16,(4,4))
print(arr1)

addition_rows = arr1[0,0:] + arr1[-1:]
addition_cols = arr1[0:,0:] + arr1[0:,-1] 
print("Row_wise_Add:",addition_rows)
print("Col_wise_Add:",addition_cols)

[[11 14  7 13]
 [12 15  4  5]
 [15  5 10  8]
 [ 6  6  4  9]]
Row_wise_Add: [[17 20 11 22]]
Col_wise_Add: [[24 19 15 22]
 [25 20 12 14]
 [28 10 18 17]
 [19 11 12 18]]
