1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

arr1 = np.random.randint(1,21,(5,5))
print(arr1)

# replace elements
print('-------------------')
arr1[:,2] = 1
print(arr1)


[[17  4  6  4 18]
 [ 2 20  2 11  4]
 [18  3  9 15 11]
 [ 3  2  8 19  7]
 [20 14 17 12 15]]
-------------------
[[17  4  1  4 18]
 [ 2 20  1 11  4]
 [18  3  1 15 11]
 [ 3  2  1 19  7]
 [20 14  1 12 15]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
arr2 = np.random.randint(1,17,(4,4))
print(arr2)

print('-------------------')
np.fill_diagonal(arr2 , 0)
print(arr2)

[[10  2  2  2]
 [13 15  8 16]
 [15  3 15 16]
 [14  1 10  1]]
-------------------
[[ 0  2  2  2]
 [13  0  8 16]
 [15  3  0 16]
 [14  1 10  0]]


3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [3]:
arr3 = np.random.randint(1,37,(6,6))
print(arr3)

print('-------------------')
print(arr3[2:5,1:4])


[[13 12  9 25 36 31]
 [ 6  6 14 19 14 13]
 [28 31 31  8  7 33]
 [31 27  9 20 26  2]
 [ 3  1 10 13 18 32]
 [29 11 17  5  5 25]]
-------------------
[[31 31  8]
 [27  9 20]
 [ 1 10 13]]


4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
arr = np.random.randint(1,26,(5,5))
print(arr)

print('-------------------')
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print(border_elements)

[[ 7 22  3 10  9]
 [ 2 19 21  1 12]
 [22  2 10 22  4]
 [ 4 20 20  3 22]
 [ 9 21  7 25 19]]
-------------------
[ 7 22  3 10  9  9 21  7 25 19  2 22  4 12  4 22]


5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [5]:
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))
print(arr1)
print("-----------------")
print(arr2)
print("Addition:")
print(arr1 + arr2)
print("Subtraction:")
print(arr1 - arr2)
print("Multiplication:")
print(arr1 * arr2)
print("Division:")
print(arr1 / arr2)


[[ 1  4 24 10]
 [27 15  7 26]
 [22 13 29  7]]
-----------------
[[24  4  9  6]
 [16  9 27 11]
 [24 12 18  7]]
Addition:
[[25  8 33 16]
 [43 24 34 37]
 [46 25 47 14]]
Subtraction:
[[-23   0  15   4]
 [ 11   6 -20  15]
 [ -2   1  11   0]]
Multiplication:
[[ 24  16 216  60]
 [432 135 189 286]
 [528 156 522  49]]
Division:
[[0.04166667 1.         2.66666667 1.66666667]
 [1.6875     1.66666667 0.25925926 2.36363636]
 [0.91666667 1.08333333 1.61111111 1.        ]]


6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

print("Using np.sum")
row_wise_addition = np.sum(arr1,axis=1)
col_wise_addition = np.sum(arr1,axis=0)
print('Row wise addition: ',row_wise_addition)
print('Col wise addition: ',col_wise_addition)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Using np.sum
Row wise addition:  [10 26 42 58]
Col wise addition:  [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [7]:
array = np.random.randint(1, 21, size=(5, 5))
print(array)
print("Mean: ",np.mean(array))
print("Median: ",np.median(array))
print("STD: ",np.std(array))
print("Variance: ",np.var(array))

[[12 19  7 19 15]
 [16  4  3  3  1]
 [14  6  3 12 12]
 [11  4  8  7 16]
 [20  7 17  9 11]]
Mean:  10.24
Median:  11.0
STD:  5.601999642984636
Variance:  31.382399999999997


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_array = (arr-mean) / std_dev

print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [9]:
arr = np.random.randint(1,10,(3,3))
print("array:\n",arr)

array_1D = np.random.randint(1,10,(3,))
print("1_D_array:\n",array_1D)

result = arr + array_1D
print("Result:\n",result)

array:
 [[3 3 6]
 [3 2 7]
 [2 2 2]]
1_D_array:
 [9 7 9]
Result:
 [[12 10 15]
 [12  9 16]
 [11  9 11]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [10]:
arr = np.random.randint(1,17,(4,4))
print("Array:\n",arr)

arr_1D = np.random.randint(1,10,(4,))
print("1D_Array:\n",arr_1D)

arr_subtract = arr - arr_1D[:,np.newaxis]
print(arr_subtract)


Array:
 [[ 5  9 10  1]
 [12 16 10 13]
 [ 9  4  8 11]
 [10 14  8  7]]
1D_Array:
 [4 1 6 1]
[[ 1  5  6 -3]
 [11 15  9 12]
 [ 3 -2  2  5]
 [ 9 13  7  6]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [11]:
arr = np.random.randint(1,10,(3,3))
print(arr)
print("Determinant:\n",np.linalg.det(arr))
print("Inverse:\n",np.linalg.inv(arr))
print("EigenValues:\n",np.linalg.eigvals(arr))


[[7 6 1]
 [1 4 9]
 [5 8 8]]
Determinant:
 -70.00000000000009
Inverse:
 [[ 0.57142857  0.57142857 -0.71428571]
 [-0.52857143 -0.72857143  0.88571429]
 [ 0.17142857  0.37142857 -0.31428571]]
EigenValues:
 [16.78558544  3.43016934 -1.21575478]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [12]:
arr1 = np.random.randint(1,9,(2,3))
arr2 = np.random.randint(1,9,(3,2))
print("Array 1:\n",arr1)
print("Array 2:\n",arr2)
result = np.dot(arr1,arr2)
print(result)

Array 1:
 [[2 4 7]
 [3 4 2]]
Array 2:
 [[6 6]
 [6 4]
 [2 7]]
[[50 77]
 [46 48]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [13]:
arr = np.random.randint(1,10,(3,3))
print(arr)
arr2 = arr.reshape(1,9)
print(arr2)
arr3 = arr.reshape(9,1)
print(arr3)

[[5 9 6]
 [7 1 9]
 [1 8 9]]
[[5 9 6 7 1 9 1 8 9]]
[[5]
 [9]
 [6]
 [7]
 [1]
 [9]
 [1]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [14]:
arr = np.random.randint(1,26,(5,5))
print(arr)
arr2 = arr.flatten()
print("________")
print(arr2)
print("________")
print(arr2.reshape(1,25))


[[13  4 22  9 21]
 [ 3 11 12  5  3]
 [17 23 23 20  8]
 [23 21  3 25 19]
 [14 23 18 18 15]]
________
[13  4 22  9 21  3 11 12  5  3 17 23 23 20  8 23 21  3 25 19 14 23 18 18
 15]
________
[[13  4 22  9 21  3 11 12  5  3 17 23 23 20  8 23 21  3 25 19 14 23 18 18
  15]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [15]:
arr = np.random.randint(1,26,size=(5,5))
print(arr)
print("__________________")
# using concatenation
print(arr[[0,0,-1,-1],[0,-1,0,-1]])


[[19 23 22  8 11]
 [ 6  8 11 10 14]
 [ 6  4 14 12 12]
 [17 21  6  5 14]
 [ 6 16  5 25 12]]
__________________
[19 11  6 12]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [16]:
arr = np.random.randint(1,20,size = (4,4))
print(arr)
arr[arr>10]=10

print(arr)

[[ 3  8 16  4]
 [ 7  9 18 10]
 [ 8  5 17  8]
 [ 7  4 12 19]]
[[ 3  8 10  4]
 [ 7  9 10 10]
 [ 8  5 10  8]
 [ 7  4 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [17]:
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([
    ('rocky',24,65.5),
    ('tocky',26,56.1),
    ('vocky',28,86.2)
],dtype=data_type)
print(data)

[('rocky', 24, 65.5) ('tocky', 26, 56.1) ('vocky', 28, 86.2)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [20]:
data_type = [('X','i4'),('Y','i4')]
data = np.array([
    (1,3),
    (2,5),
    (4,7),
    (2,4)
    ],dtype=data_type)

print(data)
cal_dist = np.sqrt((data['X'][:,np.newaxis] - data['X'])**2 + (data['Y'][:,np.newaxis] - data['Y'])**2 )
print(cal_dist)

[(1, 3) (2, 5) (4, 7) (2, 4)]
[[0.         2.23606798 5.         1.41421356]
 [2.23606798 0.         2.82842712 1.        ]
 [5.         2.82842712 0.         3.60555128]
 [1.41421356 1.         3.60555128 0.        ]]
